# base image
FROM node:lts-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add bash
RUN apk add --no-cache bash

# install and cache app dependencies
COPY package.json package-lock.json ./
RUN yarn install
RUN yarn add @vue/cli -g
RUN yarn add yaml-front-matter -g

# start app
CMD ["yarn", "serve"]
